"""
write_build_ts.py — pre-build for dpx_tc002
Generates a random 8-char hex build ID ONLY when firmware source files have changed.
Explicitly excludes auto-generated web headers (html_*.h, js_*.h) so that
running `npm run build` does NOT trigger a new ID.
"""
Import("env")
import os, re, random, string, glob

def gen_build_id():
    return ''.join(random.choices(string.hexdigits[:16], k=8)).lower()

def _is_excluded(path):
    name = os.path.basename(path)
    return (
        name == "dpx_build_id.h"
        or name.startswith("html_")
        or name.startswith("js_")
    )

def newest_mtime(patterns, base):
    """Return the highest mtime across all files matching any of the patterns."""
    best = 0
    for pattern in patterns:
        for f in glob.glob(os.path.join(base, pattern), recursive=True):
            if os.path.isfile(f) and not _is_excluded(f):
                t = os.path.getmtime(f)
                if t > best:
                    best = t
    return best

project_dir = env.subst("$PROJECT_DIR")
header      = os.path.join(project_dir, "wled00", "dpx_build_id.h")
out_dir     = os.path.join(project_dir, "build_output")

# Watch firmware source and web UI *source* files.
# Do NOT watch html_*.h / js_*.h — those are generated output from `npm run build`
# and are regenerated unconditionally (updating mtime) even when content is unchanged.
# Instead watch wled00/data/ so an actual edit to index.htm still triggers a new ID.
SOURCE_PATTERNS = [
    "usermods/dpx_matrix/**",   # our usermod (primary)
    "wled00/*.cpp",              # core firmware .cpp
    "wled00/*.h",                # core firmware .h  (html_*.h / js_*.h excluded above)
    "wled00/src/**",             # bundled dependencies
    "wled00/data/**",            # web UI source — editing index.htm triggers new ID
    "lib/**",                    # project libraries
    "pio-scripts/**",            # build scripts themselves
]

src_newest   = newest_mtime(SOURCE_PATTERNS, project_dir)
header_mtime = os.path.getmtime(header) if os.path.exists(header) else 0

if header_mtime >= src_newest and os.path.exists(header):
    # Nothing changed — reuse existing ID (do NOT write header → no recompile)
    with open(header) as f:
        m = re.search(r'"([0-9a-f]{8})"', f.read())
        build_id = m.group(1) if m else gen_build_id()
    print(f"[dpx] Build ID unchanged: {build_id}")
else:
    # Sources changed — generate new ID
    build_id = gen_build_id()
    os.makedirs(out_dir, exist_ok=True)
    with open(header, "w") as f:
        f.write("// Auto-generated by pio-scripts/write_build_ts.py — do not edit\n")
        f.write("#pragma once\n")
        f.write(f'#define DPX_BUILD_ID "{build_id}"\n')
    with open(os.path.join(out_dir, "dpx_build.ts"), "w") as f:
        f.write(build_id)
    print(f"[dpx] Build ID NEW: {build_id}")
