"""
write_build_ts.py — pre-build for dpx_tc002
Writes a random 8-char hex build ID to:
  1. wled00/dpx_build_id.h  — included by dpx_api.h so it forces recompile
  2. build_output/dpx_build.ts — read by dpx_test.sh for staleness check
Because the header changes every build, PlatformIO WILL recompile dpx_matrix.cpp
and the build_id embedded in the firmware will always match dpx_build.ts.
"""
Import("env")
import os, random, string

def gen_build_id():
    return ''.join(random.choices(string.hexdigits[:16], k=8)).lower()

build_id = gen_build_id()
project_dir = env.subst("$PROJECT_DIR")

# 1. Write the header (forces recompile of any file that includes it)
header = os.path.join(project_dir, "wled00", "dpx_build_id.h")
with open(header, "w") as f:
    f.write(f'// Auto-generated by pio-scripts/write_build_ts.py — do not edit\n')
    f.write(f'#pragma once\n')
    f.write(f'#define DPX_BUILD_ID "{build_id}"\n')

# 2. Write the test companion file
out_dir = os.path.join(project_dir, "build_output")
os.makedirs(out_dir, exist_ok=True)
with open(os.path.join(out_dir, "dpx_build.ts"), "w") as f:
    f.write(build_id)

print(f"[dpx] Build ID: {build_id}")
