// ================================================================================
// dpx_buzzer.h — Non-blocking RTTTL tone player for TC001 (GPIO 15)
// ================================================================================
// Original work — dubpixel / dpx_tc002 (EUPL v1.2)
// ================================================================================
// PROJECT: dpx_tc002_frm
// ================================================================================
//
// File: dpx_buzzer.h
// Purpose: Parses an RTTTL string into a flat note/duration sequence and steps
//          through it from loop() without any blocking delays.
//
//          Uses Arduino tone()/noTone() which on ESP32 drives a single LEDC
//          channel. This is safe alongside WS2812B LEDs because WLED drives
//          those via the RMT peripheral, not LEDC.
//
// Public API:
//   dpxBuzzerInit()              — call once from setup(); drives pin LOW
//   dpxBuzzerPlay(const char*)   — start playing an RTTTL string
//   dpxBuzzerStop()              — immediately silence and reset
//   dpxBuzzerTick()              — call every loop(); advances the sequence
//
// RTTTL format: "Title:d=4,o=5,b=120:e,e,e,c,e,g,G"
//   d = default note duration (1/2/4/8/16/32)
//   o = default octave (4–7)
//   b = BPM
//   Notes: [dur][pitch][#][oct][.]  — # = sharp, . = dotted (×1.5)
//
// ================================================================================

#pragma once
#include "Arduino.h"

// AI: below section was generated by an AI

#define DPX_BUZZER_PIN       15
#define DPX_BUZZER_MAX_NOTES 96   // max notes parsed from one RTTTL string

// ── Chromatic frequency table — octave 4 base (C4..B4, Hz) ──────────────────
// Index: 0=C  1=C#  2=D  3=D#  4=E  5=F  6=F#  7=G  8=G#  9=A  10=A#  11=B
static const uint16_t DPX_NOTE_HZ[12] PROGMEM = {
    262, 277, 294, 311, 330, 349, 370, 392, 415, 440, 466, 494
};

// Map RTTTL pitch letter → chromatic index (0-11). Returns -1 for 'p' (pause).
static int _dpxPitchIdx(char c) {
    switch (c) {
        case 'c': return 0;
        case 'd': return 2;
        case 'e': return 4;
        case 'f': return 5;
        case 'g': return 7;
        case 'a': return 9;
        case 'b': return 11;
        default:  return -1;  // 'p' = pause, unknown = silence
    }
}

struct DpxBuzzerNote {
    uint16_t freq;  // Hz — 0 means silence/pause
    uint16_t ms;    // duration in milliseconds (capped at 4000)
};

static DpxBuzzerNote  _bzNotes[DPX_BUZZER_MAX_NOTES];
static uint8_t        _bzCount    = 0;
static uint8_t        _bzIdx      = 0;
static bool           _bzPlaying  = false;
static unsigned long  _bzNoteMs   = 0;  // millis() when current note started

// ── Parse RTTTL string into _bzNotes[] ───────────────────────────────────────
static void _dpxRtttlParse(const char* rtttl) {
    _bzCount = 0;

    // Skip title (up to first ':')
    const char* p = rtttl;
    while (*p && *p != ':') p++;
    if (!*p) return;
    p++;  // skip ':'

    // Parse header defaults: d=4,o=5,b=120
    int defDur = 4, defOct = 5, bpm = 120;
    while (*p && *p != ':') {
        while (*p == ' ' || *p == ',') p++;
        if (!*p || *p == ':') break;
        char key = *p++;
        if (*p != '=') continue;
        p++;
        int val = 0;
        while (*p >= '0' && *p <= '9') val = val * 10 + (*p++ - '0');
        if      (key == 'd') defDur = max(1, val);
        else if (key == 'o') defOct = constrain(val, 4, 7);
        else if (key == 'b') bpm    = max(1, val);
    }
    if (!*p) return;
    p++;  // skip second ':'

    // Whole-note duration in ms = 60000ms/beat × 4 beats/whole = 240000/BPM
    uint32_t wholeMs = 240000UL / (uint32_t)bpm;

    while (*p && _bzCount < DPX_BUZZER_MAX_NOTES) {
        // Skip whitespace and commas between notes
        while (*p == ' ' || *p == ',') p++;
        if (!*p) break;

        // Optional explicit duration digits
        int dur = 0;
        while (*p >= '0' && *p <= '9') dur = dur * 10 + (*p++ - '0');
        if (dur == 0) dur = defDur;

        // Pitch letter (c d e f g a b p)
        if (!*p) break;
        char pitch = tolower((unsigned char)*p++);
        int  idx   = _dpxPitchIdx(pitch);

        // Optional sharp
        bool sharp = false;
        if (*p == '#') { sharp = true; p++; }

        // Optional octave digit
        int oct = defOct;
        if (*p >= '4' && *p <= '7') oct = (int)(*p++ - '0');

        // Optional dot (duration × 1.5)
        bool dotted = false;
        if (*p == '.') { dotted = true; p++; }

        // Compute duration
        uint32_t durMs = wholeMs / (uint32_t)dur;
        if (dotted) durMs = durMs * 3 / 2;
        durMs = constrain(durMs, (uint32_t)10, (uint32_t)4000);

        // Compute frequency (0 = pause)
        uint16_t freq = 0;
        if (idx >= 0) {
            int chromIdx = idx + (sharp ? 1 : 0);
            // Base frequency from table (octave 4)
            uint32_t f = pgm_read_word(&DPX_NOTE_HZ[chromIdx % 12]);
            // Octave shift relative to 4
            int shift = oct - 4 + (chromIdx / 12);
            if      (shift > 0) f <<= shift;
            else if (shift < 0) f >>= (-shift);
            freq = (uint16_t)constrain((int32_t)f, 20, 20000);
        }

        _bzNotes[_bzCount++] = { freq, (uint16_t)durMs };
    }
}

// ── Public API ────────────────────────────────────────────────────────────────
static void dpxBuzzerStop(); // forward declaration

// Call once from setup() — ensures pin is OUTPUT and driven LOW.
static void dpxBuzzerInit() {
    pinMode(DPX_BUZZER_PIN, OUTPUT);
    digitalWrite(DPX_BUZZER_PIN, LOW);
}

// Start playing an RTTTL string. Call dpxBuzzerTick() from loop() to advance.
static void dpxBuzzerPlay(const char* rtttl) {
    dpxBuzzerStop();  // stop any current melody first
    if (!rtttl || !*rtttl) return;
    _dpxRtttlParse(rtttl);
    if (_bzCount == 0) return;

    _bzIdx     = 0;
    _bzPlaying = true;
    _bzNoteMs  = millis();

    // Start the first note immediately
    if (_bzNotes[0].freq > 0) tone(DPX_BUZZER_PIN, _bzNotes[0].freq);
    else noTone(DPX_BUZZER_PIN);
}

// Immediately stop playback and silence the buzzer.
static void dpxBuzzerStop() {
    noTone(DPX_BUZZER_PIN);
    digitalWrite(DPX_BUZZER_PIN, LOW);
    _bzPlaying = false;
    _bzIdx     = 0;
    _bzCount   = 0;
}

// Advance the note sequencer — call from loop() every iteration.
static void dpxBuzzerTick() {
    if (!_bzPlaying) return;

    unsigned long now = millis();
    if (now - _bzNoteMs < _bzNotes[_bzIdx].ms) return;  // still in this note

    // Move to next note
    _bzIdx++;
    if (_bzIdx >= _bzCount) {
        dpxBuzzerStop();
        return;
    }
    _bzNoteMs = now;
    if (_bzNotes[_bzIdx].freq > 0) tone(DPX_BUZZER_PIN, _bzNotes[_bzIdx].freq);
    else noTone(DPX_BUZZER_PIN);
}

// AI: end
